### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by FlrQue** [FlrQue/rss-static-reader#3]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/pi/Services/rss-static-reader/rss_static_reader.py", line 180, in run
    self.fetched_articles: list[Union[FeedArticle]] = article_list_factory(
  File "/home/pi/Services/rss-static-reader/rss_static_reader.py", line 131, in article_list_factory
    articles.append(FeedArticle(title, article_url, published_date, author, feed_source))
  File "/home/pi/Services/rss-static-reader/rss_static_reader.py", line 99, in __init__
    self.published_date_time: datetime = datetime.datetime.strptime(published_on, datetime_format)
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-08-31T10:25:49Z' does not match format '%a, %d %b %Y %H:%M:%S %z'

**Comment by FlrQue** [comment]
At least one feed (Niebezpiecznik.pl) is affected. It is most likely due to the uncommon datetime string formatting made by feedburner service.

**Comment by FlrQue** [comment]
Fixed in commit 79335a2 and pull #4
